name: causal_engine
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch::pytorch>=2.0.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip
  - numpy
  - scipy
  - scikit-learn
  - pip:
    - einops
    - timm
    - pandas
    - matplotlib
    - seaborn
    - tqdm
    - pyyaml
    - omegaconf
