name: causal_engine
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch::pytorch>=2.0.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  - pip
  - numpy
  - scipy
  - scikit-learn
  - einops
  - timm
  - pip:
    - decord
    - av
    - pandas
    - matplotlib
    - seaborn
    - tqdm
    - pyyaml
    - omegaconf
